name: deploy-keycloak-to-vps.yml
on:
  push:
    branches:
      - vps
    paths:
      - 'keycloak/**'


jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set GIT_VERSION environment variable
        run: echo "GIT_VERSION=prod-${{ github.sha }}" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          mkdir -p deployment
          cat > deployment/.env << EOF
          # Database Credentials
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ vars.POSTGRES_USER }}
        
          
          # Git Configuration
          GIT_VERSION=${{ env.GIT_VERSION }}
          GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}
          
          # Keycloak Configuration
          KEYCLOAK_ADMIN=${{ vars.KEYCLOAK_ADMIN }}
          KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
          KEYCLOAK_HOSTNAME=${{ vars.KEYCLOAK_HOSTNAME }}
          KEYCLOAK_HOSTNAME_ADMIN=${{ vars.KEYCLOAK_HOSTNAME_ADMIN }}
          EOF

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}


      - name: Copy configuration files to VPS
        run: |
          scp -o StrictHostKeyChecking=no deployment/.env ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }}:/home/${{ vars.VPS_USERNAME }}/keycloak/
          scp -o StrictHostKeyChecking=no deployment/docker-compose.yml ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }}:/home/${{ vars.VPS_USERNAME }}/keycloak/

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }} "cd /home/${{ vars.VPS_USERNAME }}/keycloak && docker compose pull && docker compose up -d"