name: deploy-observability-to-vps.yml
on:
  push:
    branches:
      - vps
    paths:
      - 'observability/**'


jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set GIT_VERSION environment variable
        run: echo "GIT_VERSION=prod-${{ github.sha }}" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          cat > deployment/.env << EOF
          # Grafana Configuration
          GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
          GF_SECURITY_ADMIN_USER=${{ vars.GF_SECURITY_ADMIN_USER }}
          
          
          # Git Configuration
          GIT_VERSION=${{ env.GIT_VERSION }}
          GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}

          EOF

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}


      - name: Copy configuration files to VPS
        run: |
          scp -o StrictHostKeyChecking=no deployment/.env ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }}:/home/${{ vars.VPS_USERNAME }}/observability/
          scp -o StrictHostKeyChecking=no deployment/docker-compose.yml ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }}:/home/${{ vars.VPS_USERNAME }}/observability/

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }} "cd /home/${{ vars.VPS_USERNAME }}/observability && docker compose pull && docker compose up -d"